[General]
# Application name
applicationName=uFilterPickerPickBroker-test
# Controls verbosity
verbosity=3
# Main thread prints a summary at this interval
printSummaryIntervalInMinutes = 15

[Database]
# The database adds persistence to the broker.  We use sqlite3.
sqlite3File=pickStore.sqlite3
# If the database exists, then it will be deleted then recreated.
deleteIfExists=false

[Broker]
# The broker uses a queue when propagating messages from the publish
# service to the subscribe service.  This is the maximum size of that
# queue.
queueCapacity=2048
# Picks will be retained for this amount of time.  After this, they
# will be purged.
maximumPickAgeInMinutes=15

[PublishService]
# This is the frontend to which publishers send pick messages
host=0.0.0.0
port=55575
# The maximum allowable publishers before the resource is exhausted
maximumNumberOfPublishers=64
# The maximum message size in bytes.  This should be fairly small
# since pick messages aren't very big
maximumMessageSizeInBytes=128
# The maximum number of consecutive invalid messages a publisher can
# send before it is purged.
maximumNumberOfConsecutiveInvalidMessages=4

[SubscribeService]
# This is the backend from which subscribers receive pick messages
host=0.0.0.0
port=55576
# The maximum output queue size
maximumQueueSize=512
# The maximum history
